### ISSUE TITLE
LTのタイトルに文字化けがあります。

### ISSUE THREAD

**Issue by hanaokaiwa** [jjug-ccc/slides-articles-2018Fall#16]
RESTful API (JAX-RS) �書くだけで仕様書も�自動で作られていく話 with MicroProfile Open API
のタイトル部分に文字化けがありました。

**Comment by mahya8585** [comment]
https://github.com/jjug-ccc/slides-articles-2018Fall/tree/974c34e10d18d634fb2eea124626d764de9fc799
対応済み
