### ISSUE TITLE
リポジトリのDescriptionがSpringになっている

### ISSUE THREAD

**Issue by su-kun1899** [jjug-ccc/slides-articles-2018Fall#3]
![image](https://user-images.githubusercontent.com/2405082/50064520-fc6a8c80-01f4-11e9-9b68-13d82164b7c8.png)

リポジトリのDescriptionがSpringになっているようですので、Fallに修正が必要かと。

**Comment by mahya8585** [comment]
😂
ありがとうございますっw
修正したのでクローズします
